services:

  s3:
    ports:
      - "9000:9000"
      - "9001:9001"

  db:
    ports:
      - "5432:5432"

  api:
    ports:
      - "8080:8080"

  pgweb:
    image: sosedoff/pgweb
    restart: always
    ports:
      - "8081:8081"
    links:
      - db
    environment:
      - DATABASE_URL=postgres://db_user:db_password@db:5432/fullstack?sslmode=disable
    depends_on:
      db:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/"]
      interval: 10s
      timeout: 5s
      retries: 5
