FROM maven:3.9.9-eclipse-temurin-17 AS build-api
WORKDIR /app
COPY api/mvnw ./
COPY api/.mvn .mvn
COPY api/pom.xml ./
RUN ./mvnw -B dependency:go-offline
RUN ./mvnw -B dependency:resolve dependency:resolve-plugins
COPY api/src src
RUN ./mvnw -B \
    resources:resources \
    compiler:compile \
    jar:jar \
    spring-boot:repackage \
    spring-boot:start \
    springdoc-openapi:generate \
    spring-boot:stop

FROM node:latest AS build-ui
WORKDIR /app
RUN apt-get update && apt-get install -y default-jre
RUN npm install -g @angular/cli
RUN npm install @openapitools/openapi-generator-cli -g
COPY ui/package*.json ./
RUN npm install
COPY ui .
COPY --from=build-api /app/target/openapi.json openapi.json
RUN openapi-generator-cli generate \
    -i openapi.json \
    -g typescript-angular \
    -o src/app/generated/openapi \
    -c openapiconfig.json \
    --skip-validate-spec
RUN ng build --configuration=production

FROM nginx:latest AS runtime
COPY ui/certs /etc/nginx/certs
COPY ui/default.conf /etc/nginx/conf.d/default.conf
COPY --from=build-ui app/dist/ui/browser /usr/share/nginx/html
EXPOSE 80
