name: Report pages

on:
  workflow_call:

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  site:
    runs-on: ubuntu-latest

    steps:
      - name: Download OpenAPI HTML
        uses: actions/download-artifact@v4
        with:
          name: openapi-html
          path: ./site

      - name: Download Site
        uses: actions/download-artifact@v4
        with:
          name: api-site-partial
          path: ./site

      - name: Download UI Test Report
        uses: actions/download-artifact@v4
        with:
          name: ui-test-report
          path: ./site

      - name: Download UI Stats
        uses: actions/download-artifact@v4
        with:
          name: ui-stats
          path: ./site

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Upload Pages
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./site

      - name: Deploy GitHub Pages
        if: github.ref == 'refs/heads/main'
        id: deployment
        uses: actions/deploy-pages@v4

  wiki:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          repository: ${{github.repository}}
          path: ${{github.repository}}

      - name: Checkout Wiki
        uses: actions/checkout@v4
        with:
          repository: ${{github.repository}}.wiki
          path: ${{github.repository}}.wiki

      - name: Publish Wiki
        run: |
          set -e
          cd $GITHUB_WORKSPACE/${{github.repository}}.wiki
          find . -mindepth 1 -not -path './.git*' -exec rm -rf {} +
          cp -r $GITHUB_WORKSPACE/${{github.repository}}/docs/* .
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git diff-index --quiet HEAD || git commit -m "action: wiki sync (commit ${{github.sha}})" && git push
